GET http://localhost:3000


###
POST http://localhost:3000/api/register
Content-Type: application/json
 
{
    "name": "mudasir",
    "email": "mudasi423985@gmail.com",
    "password": "securePassword123@"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "mudasi423985@gmail.com",
    "password": "securePassword123@"
}