// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Debug: log the DATABASE_URL being used
const dbUrl = process.env.DATABASE_URL;
console.log('DEBUG prisma.config.ts: DATABASE_URL =', dbUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
